(test
 (name lifecycle_test)
 (libraries ditz))

(test
 (name id_prefix_test)
 (libraries ditz unix))

(test
 (name validate_id_test)
 (libraries ditz unix))

(test
 (name yaml_compat_test)
 (libraries ditz yaml))

(test
 (name dependency_test)
 (libraries ditz))

(test
 (name file_ref_test)
 (libraries ditz))

(test
 (name set_fields_test)
 (libraries ditz))

(test
 (name search_test)
 (libraries ditz))

(test
 (name git_test)
 (libraries ditz unix))

(test
 (name config_test)
 (libraries ditz unix))

(test
 (name fs_util_test)
 (libraries ditz unix))
